# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99db0b4e5e501c378d89f66e1c1b41b359c3f75e24a2f33b6479b716c02cc13e8a45ef07f86e72cf8461115a59666f34b450f0714e88c3dcba33879282373c08

test:
  secret_key_base: 730efca9351caf1ed4bbfaf418ef1fa45e9bc74d111f8a4cf3b7905b751e0662dccb09adeac82cc3489fb803091786862f92fe2109db448294e93cc8a21219f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
